### ISSUE TITLE
[Bug] Ly fails to build on zig 0.14.0-dev.1671+085cc54aa

### ISSUE THREAD

**Issue by soerlemans** [fairyglade/ly#697]
### Pre-requisites

- [X] I have looked for any other duplicate issues

### Ly version

Ly version 1.1.0-dev.98+022d146

### Observed behavior

I pulled the latest zig binary from the official website.
It failed to compile on the latest version of the zig compiler:

![image](https://github.com/user-attachments/assets/325e78a3-3860-46d8-8401-f0b79cfe9bcb)

I was able to build using 0.13 so all is well.
So I am just letting u guys know, to see if this is a common problem or intended?
I am not very familiar with Zig so it could be bug in the zig toolchain?

Version 0.14 has been released very recently (2024-09-27).

### Expected behavior

The project builds on the latest version of zig with no issues.

### Steps to reproduce

1. Use zig 0.14 to build the project.

### Relevant logs

```shell
/home/hackerman/Projects/Git/Public/ly/build.zig:93:48: error: expected type '*const fn (*Build.Step, Build.Step.MakeOptions) anyerror!void', found '*const fn (*Build.Step, Progress.Node) @typeInfo(@typeInfo(@TypeOf(build.ExeInstaller(true).make)).@"fn".return_type.?).error_union.error_set!void'
    installexe_step.makeFn = ExeInstaller(true).make;
                             ~~~~~~~~~~~~~~~~~~^~~~~
/home/hackerman/Projects/Git/Public/ly/build.zig:93:48: note: pointer type child 'fn (*Build.Step, Progress.Node) @typeInfo(@typeInfo(@TypeOf(build.ExeInstaller(true).make)).@"fn".return_type.?).error_union.error_set!void' cannot cast into pointer type child 'fn (*Build.Step, Build.Step.MakeOptions) anyerror!void'
/home/hackerman/Projects/Git/Public/ly/build.zig:93:48: note: parameter 1 'Progress.Node' cannot cast into 'Build.Step.MakeOptions'
/opt/zig-linux-x86_64-0.14.0-dev.1671+085cc54aa/lib/std/Build/Step.zig:71:25: note: struct declared here
pub const MakeOptions = struct {
                        ^~~~~~
/opt/zig-linux-x86_64-0.14.0-dev.1671+085cc54aa/lib/std/Progress.zig:80:18: note: struct declared here
pub const Node = struct {
                 ^~~~~~
referenced by:
    runBuild__anon_4825: /opt/zig-linux-x86_64-0.14.0-dev.1671+085cc54aa/lib/std/Build.zig:2168:44
    main: /opt/zig-linux-x86_64-0.14.0-dev.1671+085cc54aa/lib/compiler/build_runner.zig:335:29
    5 reference(s) hidden; use '-freference-trace=7' to see all references
/home/hackerman/.cache/zig/p/122062d301a203d003547b414237229b09a7980095061697349f8bef41be9c30266b/build.zig:83:13: error: expected type '*const fn (*Build.Step, Build.Step.MakeOptions) anyerror!void', found '*const fn (*Build.Step, Progress.Node) anyerror!void'
            }
            ^
/home/hackerman/.cache/zig/p/122062d301a203d003547b414237229b09a7980095061697349f8bef41be9c30266b/build.zig:83:13: note: pointer type child 'fn (*Build.Step, Progress.Node) anyerror!void' cannot cast into pointer type child 'fn (*Build.Step, Build.Step.MakeOptions) anyerror!void'
/home/hackerman/.cache/zig/p/122062d301a203d003547b414237229b09a7980095061697349f8bef41be9c30266b/build.zig:83:13: note: parameter 1 'Progress.Node' cannot cast into 'Build.Step.MakeOptions'
/opt/zig-linux-x86_64-0.14.0-dev.1671+085cc54aa/lib/std/Build/Step.zig:71:25: note: struct declared here
pub const MakeOptions = struct {
                        ^~~~~~
/opt/zig-linux-x86_64-0.14.0-dev.1671+085cc54aa/lib/std/Progress.zig:80:18: note: struct declared here
pub const Node = struct {
                 ^~~~~~
```

**Comment by AnErrupTion** [comment]
@soerlemans Hello! Ly doesn't currently build with nightly builds of Zig such as the latest 0.14 one. Support for 0.14 will be added however once it's fully released.

**Comment by soerlemans** [comment]
Aaah yes understandable I will close the issue.
